apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: apisix
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: apisix
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: proxy
      port: {{ .Values.service.port }}
      targetPort: proxy
